from .model import TelegramBotCommandScopeChatAdministratorsModel
from .obj import TelegramBotCommandScopeChatAdministrators
from .serializer import TelegramBotCommandScopeChatAdministratorsSerializer
