from .model import TelegramBotCommandScopeAllChatAdministratorsModel
from .obj import TelegramBotCommandScopeAllChatAdministrators
from .serializer import TelegramBotCommandScopeAllChatAdministratorsSerializer
