from .model import TelegramBotCommandScopeModel
from .obj import TelegramBotCommandScope
from .serializer import TelegramBotCommandScopeSerializer
from .bot_command_scope_serializer import BotCommandScopeObjectSerializer
